// internal/ui-podzone/src/solid/components/common/display/Alert.tsx
import { Show, type JSX, type ParentProps } from 'solid-js'
import { classes } from '../../../shared/utils'
import { type AlertTone, toneClasses } from './shared'

export { type AlertTone } from './shared'

export function Alert(
  props: ParentProps<{
    tone?: AlertTone
    title?: string
    action?: JSX.Element
    class?: string
  }>
) {
  return (
    <div
      class={classes(
        'flex flex-col gap-3 rounded-lg border px-4 py-3 shadow-sm md:flex-row md:items-start md:justify-between',
        toneClasses[props.tone ?? 'blue'],
        props.class
      )}
      role="alert"
    >
      <div class="space-y-1">
        <Show when={props.title}>
          <p class="text-sm font-semibold">{props.title}</p>
        </Show>
        <div class="text-sm">{props.children}</div>
      </div>
      <Show when={props.action}>
        <div class="shrink-0">{props.action}</div>
      </Show>
    </div>
  )
}

// frontend-v2/src/app/shared/ui/alert/alert.component.ts
import { Component, computed, input } from '@angular/core';
import { classes } from '../../utils';
import { type AlertTone, toneClasses } from '../display-shared';

export type { AlertTone };

@Component({
  selector: 'app-alert',
  templateUrl: './alert.component.html',
})
export class Alert {
  tone = input<AlertTone>('blue');
  title = input<string>();
  class = input<string>();

  protected wrapperClass = computed(() =>
    classes(
      'flex flex-col gap-3 rounded-lg border px-4 py-3 shadow-sm md:flex-row md:items-start md:justify-between',
      toneClasses[this.tone()],
      this.class(),
    ),
  );
}

<div [class]="wrapperClass()" role="alert">
  <div class="space-y-1">
    @if (title()) {
      <p class="text-sm font-semibold">{{ title() }}</p>
    }
    <div class="text-sm"><ng-content /></div>
  </div>
  <div class="shrink-0">
    <ng-content select="[action]" />
  </div>
</div>
