// internal/ui-podzone/src/solid/components/common/display/Avatar.tsx
import { Show } from 'solid-js'
import { classes } from '../../../shared/utils'
import { Indicator } from './Indicator'
import { avatarSizeClasses, type AvatarSize, initials } from './shared'

export function Avatar(props: {
  src?: string
  alt?: string
  name?: string
  size?: AvatarSize
  rounded?: boolean
  status?: 'online' | 'offline' | 'busy' | 'away'
  class?: string
}) {
  const statusColor = () => {
    if (props.status === 'busy') return 'red'
    if (props.status === 'away') return 'yellow'
    if (props.status === 'online') return 'green'
    return 'gray'
  }

  return (
    <div class={classes('relative inline-flex', props.class)}>
      <div
        class={classes(
          'inline-flex items-center justify-center overflow-hidden bg-gray-200 font-semibold text-gray-700',
          avatarSizeClasses[props.size ?? 'md'],
          props.rounded === false ? 'rounded-lg' : 'rounded-full'
        )}
      >
        <Show when={props.src} fallback={<span>{initials(props.name)}</span>}>
          <img
            src={props.src}
            alt={props.alt ?? props.name ?? 'Avatar'}
            class="h-full w-full object-cover"
          />
        </Show>
      </div>
      <Show when={props.status}>
        <Indicator
          color={statusColor()}
          class="absolute bottom-0 right-0 ring-2 ring-white"
        />
      </Show>
    </div>
  )
}

// frontend-v2/src/app/shared/ui/avatar/avatar.component.ts
import { Component, computed, input } from '@angular/core';
import { classes } from '../../utils';
import { avatarSizeClasses, initials, type AvatarSize } from '../display-shared';
import { Indicator, type IndicatorColor } from '../indicator/indicator.component';

export type { AvatarSize };

@Component({
  selector: 'app-avatar',
  imports: [Indicator],
  templateUrl: './avatar.component.html',
})
export class Avatar {
  src = input<string>();
  alt = input<string>();
  name = input<string>();
  size = input<AvatarSize>('md');
  rounded = input(true);
  status = input<'online' | 'offline' | 'busy' | 'away'>();
  class = input<string>();

  protected initialsText = computed(() => initials(this.name()));

  protected statusColor = computed<IndicatorColor>(() => {
    const status = this.status();
    if (status === 'busy') return 'red';
    if (status === 'away') return 'yellow';
    if (status === 'online') return 'green';
    return 'gray';
  });

  protected wrapperClass = computed(() => classes('relative inline-flex', this.class()));

  protected innerClass = computed(() =>
    classes(
      'inline-flex items-center justify-center overflow-hidden bg-gray-200 font-semibold text-gray-700',
      avatarSizeClasses[this.size()],
      this.rounded() ? 'rounded-full' : 'rounded-lg',
    ),
  );
}

<div [class]="wrapperClass()">
  <div [class]="innerClass()">
    @if (src()) {
      <img [src]="src()" [alt]="alt() ?? name() ?? 'Avatar'" class="h-full w-full object-cover" />
    } @else {
      <span>{{ initialsText() }}</span>
    }
  </div>
  @if (status()) {
    <app-indicator [color]="statusColor()" class="absolute bottom-0 right-0 ring-2 ring-white" />
  }
</div>
