// internal/ui-podzone/src/solid/pages/podzone/RegisterPage.tsx
import { Link, useNavigate } from '@tanstack/solid-router';
import { createSignal } from 'solid-js';
import { register } from '../../../services/auth';
import { Button, Card, InputField } from '../../components/common/Primitives';
import { ErrorAlert } from '../../components/common/Feedback';
import { SectionLead } from '../../components/common/SectionLead';

export default function RegisterPage() {
  const navigate = useNavigate();
  const [username, setUsername] = createSignal('');
  const [email, setEmail] = createSignal('');
  const [password, setPassword] = createSignal('');
  const [confirmPassword, setConfirmPassword] = createSignal('');
  const [error, setError] = createSignal('');
  const [loading, setLoading] = createSignal(false);

  const submit = async (event: SubmitEvent) => {
    event.preventDefault();

    if (password() !== confirmPassword()) {
      setError('The passwords do not match.');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const { success, data } = await register({
        username: username().trim(),
        email: email().trim(),
        password: password(),
      });

      if (!success) {
        setError(data?.message || 'Account setup failed');
        return;
      }

      void navigate({ to: '/admin', replace: true });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="mx-auto flex min-h-[calc(100vh-3rem)] max-w-6xl items-center px-4 py-10 sm:px-6 lg:px-8">
      <div class="grid w-full gap-6 lg:grid-cols-[0.9fr_1.1fr]">
        <Card class="space-y-6 bg-gray-950 text-white [&_h1]:text-white [&_p]:text-gray-300">
          <SectionLead
            eyebrow="Store Setup"
            title="Create your seller account."
            copy="Start with one account, then create stores, invite teammates, and run day-to-day POD operations from the same backoffice."
          />
          <div class="rounded-lg border border-white/10 bg-white/10 p-5 text-sm text-gray-200 shadow-sm">
            New accounts go straight into the same secure sign-in flow used by
            the rest of the backoffice.
          </div>
        </Card>

        <Card class="space-y-5">
          <div class="space-y-1">
            <h1 class="text-2xl font-semibold tracking-tight text-gray-900">
              Create account
            </h1>
            <p class="text-sm text-gray-500">
              Set up your account to create stores and manage your team.
            </p>
          </div>

          <form class="space-y-4" onSubmit={submit}>
            <InputField
              label="Username"
              value={username()}
              placeholder="store_owner"
              onInput={(event) => setUsername(event.currentTarget.value)}
            />
            <InputField
              label="Email"
              type="email"
              value={email()}
              placeholder="owner@store.com"
              onInput={(event) => setEmail(event.currentTarget.value)}
            />
            <InputField
              label="Password"
              type="password"
              value={password()}
              placeholder="Create a password"
              onInput={(event) => setPassword(event.currentTarget.value)}
            />
            <InputField
              label="Confirm password"
              type="password"
              value={confirmPassword()}
              placeholder="Repeat the password"
              onInput={(event) => setConfirmPassword(event.currentTarget.value)}
            />

            {error() ? <ErrorAlert>{error()}</ErrorAlert> : null}

            <Button
              type="submit"
              loading={loading()}
              disabled={
                !username().trim() ||
                !email().trim() ||
                !password() ||
                !confirmPassword()
              }
            >
              Create account
            </Button>
          </form>

          <p class="text-sm text-gray-500">
            Already have an account?{' '}
            <Link to="/auth/login" class="font-semibold text-gray-950">
              Sign in
            </Link>
          </p>
        </Card>
      </div>
    </div>
  );
}

// frontend-v2/src/app/features/auth/register-page/register-page.component.ts
import { Component, computed, inject, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';

import { AuthService } from '../../../core/auth/auth.service';
import { Button } from '../../../shared/ui/button/button.component';
import { Card } from '../../../shared/ui/card/card.component';
import { ErrorAlert } from '../../../shared/ui/error-alert/error-alert.component';
import { InputField } from '../../../shared/ui/input-field/input-field.component';
import { SectionLead } from '../../../shared/ui/section-lead/section-lead.component';

@Component({
  selector: 'app-register-page',
  imports: [Card, InputField, Button, ErrorAlert, SectionLead, RouterLink],
  templateUrl: './register-page.component.html',
  styleUrl: './register-page.component.scss',
})
export class RegisterPage {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  username = signal('');
  email = signal('');
  password = signal('');
  confirmPassword = signal('');
  error = signal('');
  submitting = signal(false);

  protected confirmPasswordMismatch = computed(
    () => this.confirmPassword().length > 0 && this.confirmPassword() !== this.password(),
  );

  protected canSubmit = computed(
    () =>
      !!this.username().trim() &&
      !!this.email().trim() &&
      !!this.password() &&
      !!this.confirmPassword() &&
      !this.confirmPasswordMismatch(),
  );

  async submit(event: SubmitEvent) {
    event.preventDefault();
    if (!this.canSubmit()) return;

    this.submitting.set(true);
    this.error.set('');
    try {
      const result = await this.auth.register({
        username: this.username().trim(),
        email: this.email().trim(),
        password: this.password(),
      });
      if (!result.success) {
        this.error.set(result.message);
        return;
      }
      await this.router.navigateByUrl('/admin');
    } finally {
      this.submitting.set(false);
    }
  }
}

<div class="register-page">
  <div class="register-page__grid">
    <app-card tone="inverse" class="register-page__hero">
      <app-section-lead
        eyebrow="Store Setup"
        title="Create your seller account."
        copy="Start with one account, then create stores, invite teammates, and run day-to-day POD operations from the same backoffice."
      />
      <div class="register-page__note">
        New accounts go straight into the same secure sign-in flow used by the rest of the
        backoffice.
      </div>
    </app-card>

    <app-card class="register-page__form-card">
      <div class="register-page__form-header">
        <h1 class="register-page__form-title">Create account</h1>
        <p class="register-page__form-subtitle">
          Set up your account to create stores and manage your team.
        </p>
      </div>

      <form class="register-page__form" (submit)="submit($event)">
        <app-input-field
          label="Username"
          [value]="username()"
          (valueChange)="username.set($event)"
          placeholder="store_owner"
        />
        <app-input-field
          label="Email"
          type="email"
          [value]="email()"
          (valueChange)="email.set($event)"
          placeholder="owner@store.com"
        />
        <app-input-field
          label="Password"
          type="password"
          [value]="password()"
          (valueChange)="password.set($event)"
          placeholder="Create a password"
        />
        <app-input-field
          label="Confirm password"
          type="password"
          [value]="confirmPassword()"
          (valueChange)="confirmPassword.set($event)"
          placeholder="Repeat the password"
          [error]="confirmPasswordMismatch()"
          [errorText]="confirmPasswordMismatch() ? 'Passwords do not match' : ''"
        />

        @if (error()) {
          <app-error-alert>{{ error() }}</app-error-alert>
        }

        <app-button type="submit" [loading]="submitting()" [disabled]="!canSubmit()"
          >Create account</app-button
        >
      </form>

      <p class="register-page__footer">
        Already have an account?
        <a routerLink="/login" class="register-page__footer-link">Sign in</a>
      </p>
    </app-card>
  </div>
</div>
