// internal/ui-podzone/src/solid/components/common/display/Rating.tsx
import { For } from 'solid-js'
import { classes } from '../../../shared/utils'

export function Rating(props: { value: number; max?: number; class?: string }) {
  const max = () => props.max ?? 5

  return (
    <div
      class={classes('inline-flex items-center gap-1', props.class)}
      aria-label={`Rated ${props.value} out of ${max()}`}
    >
      <For each={Array.from({ length: max() }, (_, index) => index + 1)}>
        {(item) => (
          <span
            class={classes(
              'text-lg',
              item <= props.value ? 'text-amber-400' : 'text-gray-300'
            )}
          >
            ★
          </span>
        )}
      </For>
    </div>
  )
}

// frontend-v2/src/app/shared/ui/rating/rating.component.ts
import { Component, computed, input } from '@angular/core';
import { classes } from '../../utils';

@Component({
  selector: 'app-rating',
  templateUrl: './rating.component.html',
})
export class Rating {
  value = input.required<number>();
  max = input(5);
  class = input<string>();

  protected stars = computed(() => Array.from({ length: this.max() }, (_, index) => index + 1));

  protected wrapperClass = computed(() => classes('inline-flex items-center gap-1', this.class()));
}

<div [class]="wrapperClass()" [attr.aria-label]="'Rated ' + value() + ' out of ' + max()">
  @for (item of stars(); track item) {
    <span [class]="item <= value() ? 'text-lg text-amber-400' : 'text-lg text-gray-300'">★</span>
  }
</div>
