// internal/ui-podzone/src/solid/components/common/MegaMenu.tsx
import {
  For,
  Show,
  createEffect,
  createSignal,
  onCleanup,
  type JSX,
} from 'solid-js'
import { classes } from '../../shared/utils'

export type MegaMenuLink = {
  label: string
  href: string
  description?: string
  icon?: JSX.Element
}

export type MegaMenuSection = {
  title: string
  links: MegaMenuLink[]
}

export type MegaMenuItem = {
  label: string
  href?: string
  active?: boolean
  sections?: MegaMenuSection[]
}

export function MegaMenu(props: {
  brand?: JSX.Element
  items: MegaMenuItem[]
  actions?: JSX.Element
  class?: string
}) {
  const [openIndex, setOpenIndex] = createSignal<number | null>(null)
  let container: HTMLDivElement | undefined

  createEffect(() => {
    const current = openIndex()
    if (current === null) return

    const handlePointerDown = (event: MouseEvent) => {
      if (container && !container.contains(event.target as Node)) {
        setOpenIndex(null)
      }
    }

    document.addEventListener('mousedown', handlePointerDown)
    onCleanup(() => {
      document.removeEventListener('mousedown', handlePointerDown)
    })
  })

  return (
    <div
      class={classes(
        'relative rounded-lg border border-gray-200 bg-white px-5 py-4 shadow-sm',
        props.class
      )}
      ref={(element) => (container = element)}
    >
      <div class="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
        <div class="flex items-center justify-between gap-4">
          <Show when={props.brand}>
            <div>{props.brand}</div>
          </Show>
          <Show when={props.actions}>
            <div class="xl:hidden">{props.actions}</div>
          </Show>
        </div>

        <nav class="flex flex-wrap items-center gap-2">
          <For each={props.items}>
            {(item, index) =>
              item.sections?.length ? (
                <button
                  type="button"
                  class={classes(
                    'inline-flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition',
                    item.active || openIndex() === index()
                      ? 'bg-gray-100 text-gray-950'
                      : 'text-gray-600 hover:bg-gray-100 hover:text-gray-900'
                  )}
                  onClick={() =>
                    setOpenIndex((value) =>
                      value === index() ? null : index()
                    )
                  }
                >
                  <span>{item.label}</span>
                  <span
                    class={classes(
                      'text-gray-400 transition',
                      openIndex() === index() && 'rotate-180'
                    )}
                  >
                    ⌄
                  </span>
                </button>
              ) : (
                <a
                  href={item.href}
                  class={classes(
                    'inline-flex items-center rounded-md px-3 py-2 text-sm font-medium transition',
                    item.active
                      ? 'bg-gray-950 text-white'
                      : 'text-gray-600 hover:bg-gray-100 hover:text-gray-900'
                  )}
                >
                  {item.label}
                </a>
              )
            }
          </For>
        </nav>

        <Show when={props.actions}>
          <div class="hidden xl:block">{props.actions}</div>
        </Show>
      </div>

      <Show when={openIndex() !== null}>
        <div class="absolute inset-x-4 top-full z-40 mt-3 rounded-lg border border-gray-200 bg-white p-6 shadow-xl">
          <For each={props.items[openIndex() ?? 0]?.sections ?? []}>
            {(section) => (
              <div class="mb-6 last:mb-0">
                <p class="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-gray-400">
                  {section.title}
                </p>
                <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
                  <For each={section.links}>
                    {(link) => (
                      <a
                        href={link.href}
                        class="rounded-lg border border-gray-200 px-4 py-3 transition hover:border-gray-300 hover:bg-gray-50"
                        onClick={() => setOpenIndex(null)}
                      >
                        <div class="flex items-start gap-3">
                          <Show when={link.icon}>
                            <div class="pt-0.5 text-gray-700">{link.icon}</div>
                          </Show>
                          <div class="space-y-1">
                            <p class="text-sm font-semibold text-gray-900">
                              {link.label}
                            </p>
                            <Show when={link.description}>
                              <p class="text-sm leading-6 text-gray-500">
                                {link.description}
                              </p>
                            </Show>
                          </div>
                        </div>
                      </a>
                    )}
                  </For>
                </div>
              </div>
            )}
          </For>
        </div>
      </Show>
    </div>
  )
}

// frontend-v2/src/app/shared/ui/mega-menu/mega-menu.component.ts
import { Component, ElementRef, computed, effect, input, signal, viewChild } from '@angular/core';
import { classes } from '../../utils';
// NOTE: depends on Link.tsx's Angular port, assigned to a different
// parallel porting batch. Path assumed per this project's folder-per-
// component convention — reconcile at the consolidated build pass if the
// actual path differs.
import { Link } from '../link/link.component';

export type MegaMenuLink = {
  label: string;
  href: string;
  description?: string;
  // Solid's `icon?: JSX.Element` dropped — see nav-item.ts for the same
  // simplification and reasoning.
};

export type MegaMenuSection = {
  title: string;
  links: MegaMenuLink[];
};

export type MegaMenuItem = {
  label: string;
  href?: string;
  active?: boolean;
  sections?: MegaMenuSection[];
};

@Component({
  selector: 'app-mega-menu',
  imports: [Link],
  templateUrl: './mega-menu.component.html',
})
export class MegaMenu {
  items = input.required<MegaMenuItem[]>();
  class = input<string>();
  // Solid's `brand`/`actions` (JSX.Element) become content-projection
  // slots — use <div slot="brand"> / <div slot="actions"> inside
  // <app-mega-menu>. Same "actions rendered twice" simplification as
  // Navbar applies here — see navbar.component.html's comment.

  protected openIndex = signal<number | null>(null);
  protected container = viewChild<ElementRef<HTMLDivElement>>('container');

  protected className = computed(() =>
    classes(
      'relative rounded-lg border border-gray-200 bg-white px-5 py-4 shadow-sm',
      this.class(),
    ),
  );

  protected openSections = computed(() => {
    const index = this.openIndex();
    if (index === null) return [];
    return this.items()[index]?.sections ?? [];
  });

  constructor() {
    effect((onCleanup) => {
      if (this.openIndex() === null) return;

      const handlePointerDown = (event: MouseEvent) => {
        const element = this.container()?.nativeElement;
        if (element && !element.contains(event.target as Node)) {
          this.openIndex.set(null);
        }
      };

      document.addEventListener('mousedown', handlePointerDown);
      onCleanup(() => document.removeEventListener('mousedown', handlePointerDown));
    });
  }

  protected toggleIndex(index: number) {
    this.openIndex.update((value) => (value === index ? null : index));
  }

  protected itemButtonClass(item: MegaMenuItem, index: number) {
    return classes(
      'inline-flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition',
      item.active || this.openIndex() === index
        ? 'bg-gray-100 text-gray-950'
        : 'text-gray-600 hover:bg-gray-100 hover:text-gray-900',
    );
  }

  protected chevronClass(index: number) {
    return classes('text-gray-400 transition', this.openIndex() === index && 'rotate-180');
  }

  protected linkClass(item: MegaMenuItem) {
    return classes(
      'inline-flex items-center rounded-md px-3 py-2 text-sm font-medium transition',
      item.active
        ? 'bg-gray-950 text-white'
        : 'text-gray-600 hover:bg-gray-100 hover:text-gray-900',
    );
  }

  protected closeMenu() {
    this.openIndex.set(null);
  }
}

<div [class]="className()" #container>
  <div class="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
    <div class="flex items-center justify-between gap-4">
      <div><ng-content select="[slot=brand]" /></div>
    </div>

    <nav class="flex flex-wrap items-center gap-2">
      @for (item of items(); track item.label; let index = $index) {
        @if (item.sections?.length) {
          <button type="button" [class]="itemButtonClass(item, index)" (click)="toggleIndex(index)">
            <span>{{ item.label }}</span>
            <span [class]="chevronClass(index)">⌄</span>
          </button>
        } @else {
          <app-link [href]="item.href ?? ''" [class]="linkClass(item)">{{ item.label }}</app-link>
        }
      }
    </nav>

    <div><ng-content select="[slot=actions]" /></div>
  </div>

  @if (openIndex() !== null) {
    <div
      class="absolute inset-x-4 top-full z-40 mt-3 rounded-lg border border-gray-200 bg-white p-6 shadow-xl"
    >
      @for (section of openSections(); track section.title) {
        <div class="mb-6 last:mb-0">
          <p class="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-gray-400">
            {{ section.title }}
          </p>
          <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
            @for (link of section.links; track link.href) {
              <app-link
                [href]="link.href"
                class="rounded-lg border border-gray-200 px-4 py-3 transition hover:border-gray-300 hover:bg-gray-50"
                (linkClick)="closeMenu()"
              >
                <div class="flex items-start gap-3">
                  <div class="space-y-1">
                    <p class="text-sm font-semibold text-gray-900">{{ link.label }}</p>
                    @if (link.description) {
                      <p class="text-sm leading-6 text-gray-500">{{ link.description }}</p>
                    }
                  </div>
                </div>
              </app-link>
            }
          </div>
        </div>
      }
    </div>
  }
</div>
