// internal/ui-podzone/src/solid/components/common/QrCode.tsx
import { Show, createEffect, createSignal, onCleanup } from 'solid-js';
import QRCode from 'qrcode';
import { classes } from '../../shared/utils';

export function QrCode(props: {
  value: string;
  size?: number;
  class?: string;
  panelClass?: string;
}) {
  const [svg, setSvg] = createSignal('');
  const [error, setError] = createSignal('');

  createEffect(() => {
    const nextValue = props.value.trim();
    if (!nextValue) {
      setSvg('');
      setError('');
      return;
    }

    let active = true;

    void QRCode.toString(nextValue, {
      type: 'svg',
      width: props.size ?? 192,
      margin: 1,
      errorCorrectionLevel: 'M',
      color: {
        dark: '#111827',
        light: '#FFFFFFFF',
      },
    })
      .then((value: string) => {
        if (!active) return;
        setSvg(value);
        setError('');
      })
      .catch((nextError: unknown) => {
        if (!active) return;
        setSvg('');
        setError(
          nextError instanceof Error
            ? nextError.message
            : 'Unable to generate QR code'
        );
      });

    onCleanup(() => {
      active = false;
    });
  });

  return (
    <div
      class={classes(
        'inline-flex rounded-lg border border-gray-200 bg-white p-4 shadow-sm',
        props.class
      )}
    >
      <Show
        when={svg()}
        fallback={
          <div
            class={classes(
              'flex min-h-48 min-w-48 items-center justify-center rounded-lg bg-gray-50 px-4 py-4 text-center text-sm text-gray-500',
              props.panelClass
            )}
          >
            {error() || 'Add a value to generate a QR code.'}
          </div>
        }
      >
        <div class={props.panelClass} innerHTML={svg()} />
      </Show>
    </div>
  );
}

export function QrCodeCard(props: {
  value: string;
  title?: string;
  copy?: string;
  class?: string;
}) {
  return (
    <section
      class={classes(
        'inline-flex flex-col gap-4 rounded-lg border border-gray-200 bg-white p-5 shadow-sm',
        props.class
      )}
    >
      <Show when={props.title || props.copy}>
        <div class="space-y-1">
          <Show when={props.title}>
            <h3 class="text-lg font-semibold text-gray-900">{props.title}</h3>
          </Show>
          <Show when={props.copy}>
            <p class="text-sm text-gray-500">{props.copy}</p>
          </Show>
        </div>
      </Show>
      <QrCode value={props.value} />
    </section>
  );
}

// frontend-v2/src/app/shared/ui/qr-code/qr-code.component.ts
import { Component, computed, inject, input, resource } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import QRCode from 'qrcode';
import { classes } from '../../utils';

@Component({
  selector: 'app-qr-code',
  templateUrl: './qr-code.component.html',
})
export class QrCode {
  value = input.required<string>();
  size = input<number>();
  class = input<string>();
  panelClass = input<string>();

  private sanitizer = inject(DomSanitizer);

  protected className = computed(() =>
    classes('inline-flex rounded-lg border border-gray-200 bg-white p-4 shadow-sm', this.class()),
  );
  protected emptyClass = computed(() =>
    classes(
      'flex min-h-48 min-w-48 items-center justify-center rounded-lg bg-gray-50 px-4 py-4 text-center text-sm text-gray-500',
      this.panelClass(),
    ),
  );

  protected qr = resource({
    params: () => {
      const trimmed = this.value().trim();
      return trimmed ? { value: trimmed, size: this.size() ?? 192 } : undefined;
    },
    loader: ({ params }) =>
      QRCode.toString(params.value, {
        type: 'svg',
        width: params.size,
        margin: 1,
        errorCorrectionLevel: 'M',
        color: {
          dark: '#111827',
          light: '#FFFFFFFF',
        },
      }),
  });

  protected safeSvg = computed(() => {
    const svg = this.qr.value();
    return svg ? this.sanitizer.bypassSecurityTrustHtml(svg) : null;
  });

  protected errorMessage = computed(() => {
    const error = this.qr.error();
    if (!error) return '';
    return error instanceof Error ? error.message : 'Unable to generate QR code';
  });
}

<div [class]="className()">
  @if (safeSvg(); as svg) {
    <div [class]="panelClass()" [innerHTML]="svg"></div>
  } @else {
    <div [class]="emptyClass()">
      {{ errorMessage() || 'Add a value to generate a QR code.' }}
    </div>
  }
</div>
