// internal/ui-podzone/src/solid/components/common/Breadcrumbs.tsx
import { For } from 'solid-js';
import { classes } from '../../shared/utils';

export type BreadcrumbItem = {
  label: string;
  href?: string;
  current?: boolean;
};

export function Breadcrumbs(props: {
  items: BreadcrumbItem[];
  class?: string;
}) {
  return (
    <nav aria-label="Breadcrumb" class={props.class}>
      <ol class="flex flex-wrap items-center gap-2 text-sm text-gray-500">
        <For each={props.items}>
          {(item, index) => {
            const current = () =>
              item.current || index() === props.items.length - 1;

            return (
              <>
                <li class="flex items-center gap-2">
                  {item.href && !current() ? (
                    <a
                      href={item.href}
                      class="font-medium text-gray-600 transition hover:text-gray-950"
                    >
                      {item.label}
                    </a>
                  ) : (
                    <span
                      class={classes(
                        'font-medium',
                        current() ? 'text-gray-900' : 'text-gray-600'
                      )}
                      aria-current={current() ? 'page' : undefined}
                    >
                      {item.label}
                    </span>
                  )}
                </li>
                <li
                  class="text-gray-300"
                  aria-hidden="true"
                  hidden={index() === props.items.length - 1}
                >
                  /
                </li>
              </>
            );
          }}
        </For>
      </ol>
    </nav>
  );
}

// frontend-v2/src/app/shared/ui/breadcrumbs/breadcrumbs.component.ts
import { Component, input } from '@angular/core';
import { classes } from '../../utils';
import { Link } from '../link/link.component';

export type BreadcrumbItem = {
  label: string;
  href?: string;
  current?: boolean;
};

@Component({
  selector: 'app-breadcrumbs',
  imports: [Link],
  templateUrl: './breadcrumbs.component.html',
})
export class Breadcrumbs {
  items = input.required<BreadcrumbItem[]>();
  class = input<string>();

  protected isCurrent(item: BreadcrumbItem, index: number) {
    return item.current || index === this.items().length - 1;
  }

  protected labelClass(item: BreadcrumbItem, index: number) {
    return classes('font-medium', this.isCurrent(item, index) ? 'text-gray-900' : 'text-gray-600');
  }
}

<nav aria-label="Breadcrumb" [class]="class()">
  <ol class="flex flex-wrap items-center gap-2 text-sm text-gray-500">
    <!-- Breadcrumb items have no stable id and are always rendered in a
             fixed, non-reordering structural sequence — index tracking is
             safe here, not the general-case anti-pattern. -->
    @for (item of items(); track $index) {
      <li class="flex items-center gap-2">
        @if (item.href && !isCurrent(item, $index)) {
          <app-link
            [href]="item.href"
            class="font-medium text-gray-600 transition hover:text-gray-950"
          >
            {{ item.label }}
          </app-link>
        } @else {
          <span
            [class]="labelClass(item, $index)"
            [attr.aria-current]="isCurrent(item, $index) ? 'page' : null"
          >
            {{ item.label }}
          </span>
        }
      </li>
      @if ($index !== items().length - 1) {
        <li class="text-gray-300" aria-hidden="true">/</li>
      }
    }
  </ol>
</nav>
