// frontend-v2/src/app/shared/ui/collection-controls/collection-controls.component.ts
import { Component, input } from '@angular/core';
import {
  CollectionToolbar,
  type CollectionSortOption,
} from '../collection-toolbar/collection-toolbar.component';
import {
  CollectionFilters,
  type CollectionFilterField,
} from '../collection-filters/collection-filters.component';
import { ErrorAlert } from '../error-alert/error-alert.component';
import { LoadingInline } from '../loading-inline/loading-inline.component';
import type { CollectionQuery } from '../../services/collection-types';

@Component({
  selector: 'app-collection-controls',
  imports: [CollectionToolbar, CollectionFilters, ErrorAlert, LoadingInline],
  templateUrl: './collection-controls.component.html',
})
export class CollectionControls {
  query = input.required<CollectionQuery>();
  loading = input.required<boolean>();
  error = input.required<string>();
  searchPlaceholder = input.required<string>();
  sortOptions = input.required<CollectionSortOption[]>();
  filterFields = input.required<CollectionFilterField[]>();
  updateQuery = input.required<(patch: Partial<CollectionQuery>) => void>();
}

<div class="space-y-3">
  <app-collection-toolbar
    [search]="query().search || ''"
    [searchPlaceholder]="searchPlaceholder()"
    [sortBy]="query().sortBy || 'createdAt'"
    [sortDirection]="query().sortDirection || 'SORT_DIRECTION_DESC'"
    [pageSize]="query().pageSize"
    [sortOptions]="sortOptions()"
    (searchChange)="updateQuery()({ search: $event })"
    (sortByChange)="updateQuery()({ sortBy: $event })"
    (sortDirectionChange)="updateQuery()({ sortDirection: $event })"
    (pageSizeChange)="updateQuery()({ pageSize: $event })"
  />
  <app-collection-filters
    [fields]="filterFields()"
    [filters]="query().filters || []"
    (filtersChange)="updateQuery()({ filters: $event })"
  />
  @if (error()) {
    <app-error-alert>{{ error() }}</app-error-alert>
  }
  @if (loading()) {
    <app-loading-inline label="Loading collection..." />
  }
</div>

// frontend/packages/shared/ui/components/common/CollectionControls.tsx
import { Show, type Accessor } from 'solid-js'
import type { CollectionQuery } from '../../../services/collection'
import { CollectionFilters, type CollectionFilterField } from './CollectionFilters'
import { CollectionToolbar, type CollectionSortOption } from './CollectionToolbar'
import { ErrorAlert, LoadingInline } from './Feedback'

type CollectionControlsProps = {
    query: CollectionQuery
    loading: Accessor<boolean>
    error: Accessor<string>
    searchPlaceholder: string
    sortOptions: CollectionSortOption[]
    filterFields: CollectionFilterField[]
    updateQuery: (patch: Partial<CollectionQuery>) => void
}

export function CollectionControls(props: CollectionControlsProps) {
    return (
        <div class="space-y-3">
            <CollectionToolbar
                search={props.query.search || ''}
                searchPlaceholder={props.searchPlaceholder}
                sortBy={props.query.sortBy || 'createdAt'}
                sortDirection={props.query.sortDirection || 'SORT_DIRECTION_DESC'}
                pageSize={props.query.pageSize}
                sortOptions={props.sortOptions}
                onSearch={(search) => props.updateQuery({ search })}
                onSortByChange={(sortBy) => props.updateQuery({ sortBy })}
                onSortDirectionChange={(sortDirection) => props.updateQuery({ sortDirection })}
                onPageSizeChange={(pageSize) => props.updateQuery({ pageSize })}
            />
            <CollectionFilters
                fields={props.filterFields}
                filters={props.query.filters || []}
                onChange={(filters) => props.updateQuery({ filters })}
            />
            <Show when={props.error()}>
                <ErrorAlert>{props.error()}</ErrorAlert>
            </Show>
            <Show when={props.loading()}>
                <LoadingInline label="Loading collection..." />
            </Show>
        </div>
    )
}
