// frontend-v2/src/app/shared/ui/accordion/accordion.component.ts
import { Component, computed, input } from '@angular/core';
import { classes } from '../../utils';

// NOTE (port judgment call): Solid's AccordionItem.content is `JSX.Element`
// — arbitrary rich content per item. Angular has no direct equivalent for
// "rich content inside a data array" without a TemplateRef-based API, which
// is a bigger structural change than a faithful port. Typed as `string`
// here; upgrade to a `TemplateRef`-per-item API if rich per-item content is
// actually needed later.
export type AccordionItem = {
  title: string;
  content: string;
  description?: string;
  defaultOpen?: boolean;
  badge?: string;
};

@Component({
  selector: 'app-accordion',
  templateUrl: './accordion.component.html',
})
export class Accordion {
  items = input.required<AccordionItem[]>();
  class = input<string>();

  protected wrapperClass = computed(() =>
    classes(
      'divide-y divide-gray-200 overflow-hidden rounded-lg border border-gray-200 bg-white',
      this.class(),
    ),
  );
}

<div [class]="wrapperClass()">
  @for (item of items(); track item.title) {
    <details [open]="item.defaultOpen" class="group px-5 py-4">
      <summary class="flex cursor-pointer list-none items-start justify-between gap-4">
        <div class="space-y-1">
          <div class="flex flex-wrap items-center gap-2">
            <h3 class="text-sm font-semibold text-gray-900">{{ item.title }}</h3>
            @if (item.badge) {
              <span
                class="rounded-full bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-600"
                >{{ item.badge }}</span
              >
            }
          </div>
          @if (item.description) {
            <p class="text-sm text-gray-500">{{ item.description }}</p>
          }
        </div>
        <span class="pt-0.5 text-gray-400 transition group-open:rotate-180">⌄</span>
      </summary>
      <div class="mt-4 text-sm leading-6 text-gray-600">{{ item.content }}</div>
    </details>
  }
</div>

// internal/ui-podzone/src/solid/components/common/display/Accordion.tsx
import { For, Show, type JSX } from 'solid-js'
import { classes } from '../../../shared/utils'

export type AccordionItem = {
  title: string
  content: JSX.Element
  description?: string
  defaultOpen?: boolean
  badge?: string
}

export function Accordion(props: { items: AccordionItem[]; class?: string }) {
  return (
    <div
      class={classes(
        'divide-y divide-gray-200 overflow-hidden rounded-2xl border border-gray-200 bg-white',
        props.class
      )}
    >
      <For each={props.items}>
        {(item) => (
          <details open={item.defaultOpen} class="group px-5 py-4">
            <summary class="flex cursor-pointer list-none items-start justify-between gap-4">
              <div class="space-y-1">
                <div class="flex flex-wrap items-center gap-2">
                  <h3 class="text-sm font-semibold text-gray-900">{item.title}</h3>
                  <Show when={item.badge}>
                    <span class="rounded-full bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-600">
                      {item.badge}
                    </span>
                  </Show>
                </div>
                <Show when={item.description}>
                  <p class="text-sm text-gray-500">{item.description}</p>
                </Show>
              </div>
              <span class="pt-0.5 text-gray-400 transition group-open:rotate-180">⌄</span>
            </summary>
            <div class="mt-4 text-sm leading-6 text-gray-600">{item.content}</div>
          </details>
        )}
      </For>
    </div>
  )
}
