// frontend-v2/src/app/shared/ui/list-group/list-group.component.ts
import { NgTemplateOutlet } from '@angular/common';
import { Component, computed, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { classes } from '../../utils';

// NOTE (port judgment call): Solid's ListGroupItem.prefix/suffix are
// `JSX.Element` — arbitrary icon/content slots per array item. Angular has
// no direct equivalent without a TemplateRef-per-item API (a bigger
// structural change than a faithful port). Dropped here; label/description/
// href/active/onClick are ported. Add a TemplateRef-based prefix/suffix API
// later if a consumer actually needs per-item icons.
export type ListGroupItem = {
  label: string;
  description?: string;
  href?: string;
  active?: boolean;
  onClick?: () => void;
};

@Component({
  selector: 'app-list-group',
  imports: [RouterLink, NgTemplateOutlet],
  templateUrl: './list-group.component.html',
})
export class ListGroup {
  items = input.required<ListGroupItem[]>();
  class = input<string>();

  protected wrapperClass = computed(() =>
    classes('overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm', this.class()),
  );

  protected itemClass(item: ListGroupItem) {
    return classes(
      'flex w-full items-center justify-between gap-4 border-b border-gray-100 px-4 py-3 text-left transition last:border-b-0',
      item.active ? 'bg-blue-50 text-blue-900' : 'text-gray-700 hover:bg-gray-50',
    );
  }
}

<div [class]="wrapperClass()">
  @for (item of items(); track item.label) {
    @if (item.href) {
      <a [routerLink]="item.href" [class]="itemClass(item)">
        <ng-container *ngTemplateOutlet="itemContent; context: { $implicit: item }" />
      </a>
    } @else if (item.onClick) {
      <button type="button" [class]="itemClass(item)" (click)="item.onClick()">
        <ng-container *ngTemplateOutlet="itemContent; context: { $implicit: item }" />
      </button>
    } @else {
      <div [class]="itemClass(item)">
        <ng-container *ngTemplateOutlet="itemContent; context: { $implicit: item }" />
      </div>
    }
  }
</div>

<ng-template #itemContent let-item>
  <div class="min-w-0">
    <p class="truncate text-sm font-medium">{{ item.label }}</p>
    @if (item.description) {
      <p class="mt-1 text-sm text-gray-500">{{ item.description }}</p>
    }
  </div>
</ng-template>

// internal/ui-podzone/src/solid/components/common/display/ListGroup.tsx
import { For, Show, type JSX } from 'solid-js'
import { classes } from '../../../shared/utils'

export type ListGroupItem = {
  label: string
  description?: string
  href?: string
  prefix?: JSX.Element
  suffix?: JSX.Element
  active?: boolean
  onClick?: () => void
}

export function ListGroup(props: { items: ListGroupItem[]; class?: string }) {
  return (
    <div
      class={classes(
        'overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm',
        props.class
      )}
    >
      <For each={props.items}>
        {(item) => {
          const itemClass = classes(
            'flex w-full items-center justify-between gap-4 border-b border-gray-100 px-4 py-3 text-left transition last:border-b-0',
            item.active ? 'bg-blue-50 text-blue-900' : 'text-gray-700 hover:bg-gray-50'
          )

          const content = (
            <>
              <div class="flex min-w-0 items-start gap-3">
                <Show when={item.prefix}>
                  <div class="pt-0.5">{item.prefix}</div>
                </Show>
                <div class="min-w-0">
                  <p class="truncate text-sm font-medium">{item.label}</p>
                  <Show when={item.description}>
                    <p class="mt-1 text-sm text-gray-500">{item.description}</p>
                  </Show>
                </div>
              </div>
              <Show when={item.suffix}>
                <div class="shrink-0">{item.suffix}</div>
              </Show>
            </>
          )

          return item.href ? (
            <a href={item.href} class={itemClass}>
              {content}
            </a>
          ) : item.onClick ? (
            <button type="button" class={itemClass} onClick={item.onClick}>
              {content}
            </button>
          ) : (
            <div class={itemClass}>{content}</div>
          )
        }}
      </For>
    </div>
  )
}
