// frontend-v2/src/app/shared/ui/code-block/code-block.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-code-block',
  templateUrl: './code-block.component.html',
})
export class CodeBlock {
  code = input.required<string>();
  label = input<string>();
  class = input<string>();
}

<div [class]="class()">
  @if (label()) {
    <div class="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-500">
      {{ label() }}
    </div>
  }
  <pre class="overflow-x-auto rounded-md bg-gray-900 p-4 text-xs text-gray-100">{{
    code() || '—'
  }}</pre>
</div>

// internal/ui-podzone/src/solid/components/common/CodeBlock.tsx
import { Show } from 'solid-js'

export function CodeBlock(props: { code: string; label?: string; class?: string }) {
    return (
        <div class={props.class}>
            <Show when={props.label}>
                <div class="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-500">{props.label}</div>
            </Show>
            <pre class="overflow-x-auto rounded-md bg-gray-900 p-4 text-xs text-gray-100">{props.code || '—'}</pre>
        </div>
    )
}
