// frontend-v2/src/app/shared/ui/form-section/form-section.component.ts
import { Component, computed, input } from '@angular/core';
import { classes } from '../../utils';

@Component({
  selector: 'app-form-section',
  templateUrl: './form-section.component.html',
})
export class FormSection {
  title = input.required<string>();
  description = input<string>();
  class = input<string>();
  contentClass = input<string>();

  protected className = computed(() =>
    classes('rounded-lg border border-gray-200 bg-white p-5 shadow-sm', this.class()),
  );
  protected contentClassName = computed(() => classes('mt-6 space-y-5', this.contentClass()));
}

<section [class]="className()">
  <div
    class="flex flex-col gap-4 border-b border-gray-100 pb-4 md:flex-row md:items-start md:justify-between"
  >
    <div class="space-y-1">
      <h2 class="text-base font-semibold text-gray-950">{{ title() }}</h2>
      @if (description()) {
        <p class="max-w-2xl text-sm text-gray-600">{{ description() }}</p>
      }
    </div>
    <div class="shrink-0">
      <ng-content select="[aside]" />
    </div>
  </div>

  <div [class]="contentClassName()">
    <ng-content />
  </div>
</section>

// internal/ui-podzone/src/solid/components/common/FormSection.tsx
import type { JSX, ParentProps } from 'solid-js';
import { classes } from '../../shared/utils';

export function FormSection(
  props: ParentProps<{
    title: string;
    description?: string;
    aside?: JSX.Element;
    class?: string;
    contentClass?: string;
  }>
) {
  return (
    <section
      class={classes(
        'rounded-lg border border-gray-200 bg-white p-5 shadow-sm',
        props.class
      )}
    >
      <div class="flex flex-col gap-4 border-b border-gray-100 pb-4 md:flex-row md:items-start md:justify-between">
        <div class="space-y-1">
          <h2 class="text-base font-semibold text-gray-950">{props.title}</h2>
          {props.description ? (
            <p class="max-w-2xl text-sm text-gray-600">{props.description}</p>
          ) : null}
        </div>
        {props.aside ? <div class="shrink-0">{props.aside}</div> : null}
      </div>

      <div class={classes('mt-6 space-y-5', props.contentClass)}>
        {props.children}
      </div>
    </section>
  );
}
