// frontend-v2/src/app/shared/ui/pagination/pagination.component.ts
import { Component, computed, input, output } from '@angular/core';
import { classes } from '../../utils';
import { Button } from '../button/button.component';
import { Spinner } from '../spinner/spinner.component';

type PageItem = number | 'ellipsis';

function buildPageItems(page: number, totalPages: number): PageItem[] {
  if (totalPages <= 7) {
    return Array.from({ length: totalPages }, (_, index) => index + 1);
  }

  const pages = new Set<number>([1, totalPages, page - 1, page, page + 1]);
  const visible = [...pages]
    .filter((value) => value >= 1 && value <= totalPages)
    .sort((a, b) => a - b);
  const items: PageItem[] = [];

  for (const value of visible) {
    const previous = items[items.length - 1];
    if (typeof previous === 'number' && value - previous > 1) {
      items.push('ellipsis');
    }
    items.push(value);
  }

  return items;
}

// Page-number buttons are raw <button> elements, not <app-button>, so
// [attr.aria-current] can be set directly on the real interactive element —
// setting it on <app-button> from outside would land on that component's
// host tag, not the <button>/<a> it renders internally, which is not what
// a screen reader needs (see ANGULAR_STYLE_GUIDE.md's Pagination buttons
// rule). Classes below are copied from Button's pill/xs/dark/alternative
// variants to keep the exact same visual output.
const pageButtonBase =
  'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-full font-medium focus:outline-none focus:ring-2 disabled:pointer-events-none disabled:opacity-60 h-8 px-3 text-xs';
const pageButtonActive = 'bg-gray-950 text-white hover:bg-gray-800 focus:ring-gray-300';
const pageButtonInactive =
  'border border-gray-300 bg-white text-gray-900 hover:bg-gray-50 focus:ring-gray-200';

@Component({
  selector: 'app-pagination',
  imports: [Button, Spinner],
  templateUrl: './pagination.component.html',
})
export class Pagination {
  page = input.required<number>();
  pageSize = input.required<number>();
  total = input.required<number>();
  loading = input(false);
  class = input<string>();

  pageChange = output<number>();

  // Angular templates can't call global functions directly — expose as a
  // class member so [prevPage]="Math.max(...)"-style expressions resolve.
  protected readonly Math = Math;

  protected totalPages = computed(() => Math.max(1, Math.ceil(this.total() / this.pageSize())));
  protected start = computed(() =>
    this.total() === 0 ? 0 : (this.page() - 1) * this.pageSize() + 1,
  );
  protected finish = computed(() => Math.min(this.page() * this.pageSize(), this.total()));
  protected items = computed(() => buildPageItems(this.page(), this.totalPages()));

  protected containerClass = computed(() =>
    classes(
      'flex flex-col gap-4 border-t border-gray-100 pt-4 md:flex-row md:items-center md:justify-between',
      this.class(),
    ),
  );

  protected pageButtonClass(item: number) {
    return classes(pageButtonBase, item === this.page() ? pageButtonActive : pageButtonInactive);
  }

  protected changePage(event: MouseEvent, page: number) {
    event.preventDefault();
    event.stopPropagation();
    if (this.loading() || page === this.page()) return;
    this.pageChange.emit(page);
  }
}

@if (totalPages() > 1) {
  <div [class]="containerClass()">
    <p class="text-sm text-gray-500">Showing {{ start() }}-{{ finish() }} of {{ total() }}</p>

    <div class="flex flex-wrap items-center gap-2">
      <app-button
        type="button"
        [pill]="true"
        size="xs"
        color="alternative"
        [disabled]="loading() || page() <= 1"
        (buttonClick)="changePage($event, Math.max(1, page() - 1))"
      >
        Previous
      </app-button>

      <div class="flex flex-wrap items-center gap-2">
        @for (item of items(); track $index) {
          @if (item === 'ellipsis') {
            <span class="px-2 text-sm text-gray-400">...</span>
          } @else {
            <button
              type="button"
              [class]="pageButtonClass(item)"
              [disabled]="loading()"
              [attr.aria-current]="item === page() ? 'page' : null"
              (click)="changePage($event, item)"
            >
              @if (loading() && item === page()) {
                <app-spinner class="size-3.5" />
              }
              {{ item }}
            </button>
          }
        }
      </div>

      <app-button
        type="button"
        [pill]="true"
        size="xs"
        color="alternative"
        [disabled]="loading() || page() >= totalPages()"
        (buttonClick)="changePage($event, Math.min(totalPages(), page() + 1))"
      >
        Next
      </app-button>
    </div>
  </div>
}

// internal/ui-podzone/src/solid/components/common/Pagination.tsx
import { For, Show, createMemo } from 'solid-js'
import { classes } from '../../shared/utils'
import { Button } from './Primitives'

type PaginationProps = {
    page: number
    pageSize: number
    total: number
    loading?: boolean
    class?: string
    onPageChange: (page: number) => void
}

function buildPageItems(page: number, totalPages: number) {
    if (totalPages <= 7) {
        return Array.from({ length: totalPages }, (_, index) => index + 1)
    }

    const pages = new Set<number>([1, totalPages, page - 1, page, page + 1])
    const visible = [...pages].filter((value) => value >= 1 && value <= totalPages).sort((a, b) => a - b)
    const items: Array<number | 'ellipsis'> = []

    for (const value of visible) {
        const previous = items[items.length - 1]
        if (typeof previous === 'number' && value - previous > 1) {
            items.push('ellipsis')
        }
        items.push(value)
    }

    return items
}

export function Pagination(props: PaginationProps) {
    const totalPages = createMemo(() => Math.max(1, Math.ceil(props.total / props.pageSize)))
    const start = createMemo(() => (props.total === 0 ? 0 : (props.page - 1) * props.pageSize + 1))
    const finish = createMemo(() => Math.min(props.page * props.pageSize, props.total))
    const items = createMemo(() => buildPageItems(props.page, totalPages()))
    const changePage = (event: MouseEvent, page: number) => {
        event.preventDefault()
        event.stopPropagation()
        if (props.loading || page === props.page) return
        props.onPageChange(page)
    }

    return (
        <Show when={totalPages() > 1}>
            <div
                class={classes(
                    'flex flex-col gap-4 border-t border-gray-100 pt-4 md:flex-row md:items-center md:justify-between',
                    props.class
                )}
            >
                <p class="text-sm text-gray-500">
                    Showing {start()}-{finish()} of {props.total}
                </p>

                <div class="flex flex-wrap items-center gap-2">
                    <Button
                        type="button"
                        pill
                        size="xs"
                        color="alternative"
                        disabled={props.loading || props.page <= 1}
                        onClick={(event) => changePage(event, Math.max(1, props.page - 1))}
                    >
                        Previous
                    </Button>

                    <div class="flex flex-wrap items-center gap-2">
                        <For each={items()}>
                            {(item) =>
                                item === 'ellipsis' ? (
                                    <span class="px-2 text-sm text-gray-400">...</span>
                                ) : (
                                    <Button
                                        type="button"
                                        pill
                                        size="xs"
                                        color={item === props.page ? 'dark' : 'alternative'}
                                        loading={props.loading && item === props.page}
                                        disabled={props.loading}
                                        aria-current={item === props.page ? 'page' : undefined}
                                        onClick={(event) => changePage(event, item)}
                                    >
                                        {item}
                                    </Button>
                                )
                            }
                        </For>
                    </div>

                    <Button
                        type="button"
                        pill
                        size="xs"
                        color="alternative"
                        disabled={props.loading || props.page >= totalPages()}
                        onClick={(event) => changePage(event, Math.min(totalPages(), props.page + 1))}
                    >
                        Next
                    </Button>
                </div>
            </div>
        </Show>
    )
}
