// internal/ui-podzone/src/solid/components/common/display/Indicator.tsx
import { Show } from 'solid-js'
import { classes } from '../../../shared/utils'
import { indicatorClasses } from './shared'

export function Indicator(props: {
    color?: 'blue' | 'green' | 'yellow' | 'red' | 'gray'
    ping?: boolean
    class?: string
}) {
    return (
        <span class={classes('relative inline-flex size-3', props.class)}>
            <Show when={props.ping}>
                <span
                    class={classes(
                        'absolute inline-flex h-full w-full animate-ping rounded-full opacity-75',
                        indicatorClasses[props.color ?? 'green']
                    )}
                />
            </Show>
            <span
                class={classes('relative inline-flex size-3 rounded-full', indicatorClasses[props.color ?? 'green'])}
            />
        </span>
    )
}

// frontend-v2/src/app/shared/ui/indicator/indicator.component.ts
import { Component, computed, input } from '@angular/core';
import { classes } from '../../utils';
import { indicatorClasses } from '../display-shared';

export type IndicatorColor = 'blue' | 'green' | 'yellow' | 'red' | 'gray';

@Component({
  selector: 'app-indicator',
  templateUrl: './indicator.component.html',
})
export class Indicator {
  color = input<IndicatorColor>('green');
  ping = input(false);
  class = input<string>();

  protected wrapperClass = computed(() => classes('relative inline-flex size-3', this.class()));

  protected pingClass = computed(() =>
    classes(
      'absolute inline-flex h-full w-full animate-ping rounded-full opacity-75',
      indicatorClasses[this.color()],
    ),
  );

  protected dotClass = computed(() =>
    classes('relative inline-flex size-3 rounded-full', indicatorClasses[this.color()]),
  );
}

<span [class]="wrapperClass()">
  @if (ping()) {
    <span [class]="pingClass()"></span>
  }
  <span [class]="dotClass()"></span>
</span>
