// internal/ui-podzone/src/solid/components/common/PanelHeader.tsx
import type { JSX } from 'solid-js'
import { classes } from '../../shared/utils'

export function PanelHeader(props: {
  title: string
  copy?: string
  action?: JSX.Element
  class?: string
}) {
  return (
    <div
      class={classes(
        'flex flex-col gap-4 md:flex-row md:items-start md:justify-between',
        props.class
      )}
    >
      <div class="space-y-1">
        <h2 class="text-xl font-semibold tracking-tight text-gray-900">{props.title}</h2>
        {props.copy ? <p class="text-sm text-gray-500">{props.copy}</p> : null}
      </div>
      {props.action ? <div class="shrink-0">{props.action}</div> : null}
    </div>
  )
}

// frontend-v2/src/app/shared/ui/panel-header/panel-header.component.ts
import { Component, computed, input } from '@angular/core';
import { classes } from '../../utils';

@Component({
  selector: 'app-panel-header',
  templateUrl: './panel-header.component.html',
})
export class PanelHeader {
  title = input.required<string>();
  copy = input<string>();
  class = input<string>();

  protected className = computed(() =>
    classes('flex flex-col gap-4 md:flex-row md:items-start md:justify-between', this.class()),
  );
}

<div [class]="className()">
  <div class="space-y-1">
    <h2 class="text-xl font-semibold tracking-tight text-gray-900">{{ title() }}</h2>
    @if (copy()) {
      <p class="text-sm text-gray-500">{{ copy() }}</p>
    }
  </div>
  <div class="shrink-0">
    <ng-content select="[action]" />
  </div>
</div>
