// internal/ui-podzone/src/solid/components/common/display/Toast.tsx
import { Show, type JSX, type ParentProps } from 'solid-js'
import { classes } from '../../../shared/utils'
import { type AlertTone, toneClasses } from './shared'

export function Toast(
  props: ParentProps<{
    show?: boolean
    tone?: AlertTone
    title?: string
    fixed?: boolean
    action?: JSX.Element
    onClose?: () => void
    class?: string
  }>
) {
  return (
    <Show when={props.show ?? true}>
      <div
        class={classes(
          'z-50 flex max-w-sm items-start justify-between gap-4 rounded-lg border bg-white px-4 py-3 shadow-xl',
          props.fixed !== false && 'fixed bottom-4 right-4',
          toneClasses[props.tone ?? 'dark'],
          props.class
        )}
        role="status"
      >
        <div class="space-y-1">
          <Show when={props.title}>
            <p class="text-sm font-semibold">{props.title}</p>
          </Show>
          <div class="text-sm">{props.children}</div>
        </div>
        <div class="flex items-start gap-2">
          <Show when={props.action}>
            <div class="shrink-0">{props.action}</div>
          </Show>
          <Show when={props.onClose}>
            <button
              type="button"
              class="rounded-full px-2 py-1 text-sm font-medium text-gray-500 hover:bg-white/70 hover:text-gray-900"
              onClick={() => props.onClose?.()}
              aria-label="Close toast"
            >
              ✕
            </button>
          </Show>
        </div>
      </div>
    </Show>
  )
}

// frontend-v2/src/app/shared/ui/toast/toast.component.ts
import { Component, computed, input, output } from '@angular/core';
import { classes } from '../../utils';
import { type AlertTone, toneClasses } from '../display-shared';

// NOTE (port judgment call): Solid's close button visibility is driven by
// whether an `onClose` callback prop was passed at all
// (`<Show when={props.onClose}>`). Angular can't inspect "is anyone
// listening to this output" the same way, so this exposes an explicit
// `closable` input (default true) instead — caller sets `[closable]=false`
// to hide the button rather than simply not binding `(close)`.
@Component({
  selector: 'app-toast',
  templateUrl: './toast.component.html',
})
export class Toast {
  show = input(true);
  tone = input<AlertTone>('dark');
  title = input<string>();
  fixed = input(true);
  closable = input(true);
  class = input<string>();

  close = output<void>();

  protected wrapperClass = computed(() =>
    classes(
      'z-50 flex max-w-sm items-start justify-between gap-4 rounded-lg border bg-white px-4 py-3 shadow-xl',
      this.fixed() && 'fixed bottom-4 right-4',
      toneClasses[this.tone()],
      this.class(),
    ),
  );
}

@if (show()) {
  <div [class]="wrapperClass()" role="status">
    <div class="space-y-1">
      @if (title()) {
        <p class="text-sm font-semibold">{{ title() }}</p>
      }
      <div class="text-sm"><ng-content /></div>
    </div>
    <div class="flex items-start gap-2">
      <ng-content select="[action]" />
      @if (closable()) {
        <button
          type="button"
          class="rounded-full px-2 py-1 text-sm font-medium text-gray-500 hover:bg-white/70 hover:text-gray-900"
          (click)="close.emit()"
          aria-label="Close toast"
        >
          ✕
        </button>
      }
    </div>
  </div>
}
