// internal/ui-podzone/src/solid/components/common/display/ProgressBar.tsx
import { Show, createMemo } from 'solid-js'
import { classes } from '../../../shared/utils'
import { type AlertTone, toneFillClasses } from './shared'

export function ProgressBar(props: {
  value: number
  max?: number
  label?: string
  tone?: AlertTone
  showValue?: boolean
  class?: string
}) {
  const percent = createMemo(() => {
    const max = props.max ?? 100
    if (max <= 0) return 0
    return Math.max(0, Math.min(100, Math.round((props.value / max) * 100)))
  })

  return (
    <div class={classes('space-y-2', props.class)}>
      <Show when={props.label || props.showValue}>
        <div class="flex items-center justify-between gap-4 text-sm">
          <Show when={props.label}>
            <span class="font-medium text-gray-700">{props.label}</span>
          </Show>
          <Show when={props.showValue}>
            <span class="text-gray-500">{percent()}%</span>
          </Show>
        </div>
      </Show>
      <div class="h-2.5 overflow-hidden rounded-full bg-gray-200">
        <div
          class={classes(
            'h-full rounded-full transition-[width]',
            toneFillClasses[props.tone ?? 'blue']
          )}
          style={{ width: `${percent()}%` }}
        />
      </div>
    </div>
  )
}

// frontend-v2/src/app/shared/ui/progress-bar/progress-bar.component.ts
import { Component, computed, input } from '@angular/core';
import { classes } from '../../utils';
import { type AlertTone, toneFillClasses } from '../display-shared';

@Component({
  selector: 'app-progress-bar',
  templateUrl: './progress-bar.component.html',
})
export class ProgressBar {
  value = input.required<number>();
  max = input(100);
  label = input<string>();
  tone = input<AlertTone>('blue');
  showValue = input(false);
  class = input<string>();

  protected percent = computed(() => {
    const max = this.max();
    if (max <= 0) return 0;
    return Math.max(0, Math.min(100, Math.round((this.value() / max) * 100)));
  });

  protected wrapperClass = computed(() => classes('space-y-2', this.class()));

  protected fillClass = computed(() =>
    classes('h-full rounded-full transition-[width]', toneFillClasses[this.tone()]),
  );
}

<div [class]="wrapperClass()">
  @if (label() || showValue()) {
    <div class="flex items-center justify-between gap-4 text-sm">
      @if (label()) {
        <span class="font-medium text-gray-700">{{ label() }}</span>
      }
      @if (showValue()) {
        <span class="text-gray-500">{{ percent() }}%</span>
      }
    </div>
  }
  <div class="h-2.5 overflow-hidden rounded-full bg-gray-200">
    <div [class]="fillClass()" [style.width.%]="percent()"></div>
  </div>
</div>
