// internal/ui-podzone/src/solid/components/common/CollectionToolbar.tsx
import { createSignal, For } from 'solid-js'
import { Button } from './Primitives'

export type CollectionSortOption = {
    label: string
    value: string
}

type CollectionToolbarProps = {
    search: string
    searchPlaceholder: string
    sortBy: string
    sortDirection: 'SORT_DIRECTION_ASC' | 'SORT_DIRECTION_DESC'
    pageSize: number
    sortOptions: CollectionSortOption[]
    onSearch: (value: string) => void
    onSortByChange: (value: string) => void
    onSortDirectionChange: (value: 'SORT_DIRECTION_ASC' | 'SORT_DIRECTION_DESC') => void
    onPageSizeChange: (value: number) => void
}

export function CollectionToolbar(props: CollectionToolbarProps) {
    const [searchDraft, setSearchDraft] = createSignal(props.search)

    const submitSearch = (event: SubmitEvent) => {
        event.preventDefault()
        props.onSearch(searchDraft().trim())
    }

    return (
        <form class="grid gap-3 lg:grid-cols-[minmax(14rem,1fr)_minmax(10rem,0.5fr)_auto_auto]" onSubmit={submitSearch}>
            <label class="space-y-1 text-sm text-gray-600">
                <span class="font-medium text-gray-800">Search</span>
                <div class="flex gap-2">
                    <input
                        type="search"
                        value={searchDraft()}
                        placeholder={props.searchPlaceholder}
                        class="min-w-0 flex-1 rounded-md border border-gray-300 px-3 py-2 text-sm"
                        onInput={(event) => setSearchDraft(event.currentTarget.value)}
                    />
                    <Button type="submit" color="alternative" size="sm">
                        Search
                    </Button>
                </div>
            </label>

            <label class="space-y-1 text-sm text-gray-600">
                <span class="font-medium text-gray-800">Sort</span>
                <select
                    value={props.sortBy}
                    class="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                    onChange={(event) => props.onSortByChange(event.currentTarget.value)}
                >
                    <For each={props.sortOptions}>
                        {(option) => <option value={option.value}>{option.label}</option>}
                    </For>
                </select>
            </label>

            <label class="space-y-1 text-sm text-gray-600">
                <span class="font-medium text-gray-800">Direction</span>
                <select
                    value={props.sortDirection}
                    class="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                    onChange={(event) =>
                        props.onSortDirectionChange(
                            event.currentTarget.value as 'SORT_DIRECTION_ASC' | 'SORT_DIRECTION_DESC'
                        )
                    }
                >
                    <option value="SORT_DIRECTION_DESC">Descending</option>
                    <option value="SORT_DIRECTION_ASC">Ascending</option>
                </select>
            </label>

            <label class="space-y-1 text-sm text-gray-600">
                <span class="font-medium text-gray-800">Rows</span>
                <select
                    value={props.pageSize}
                    class="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                    onChange={(event) => props.onPageSizeChange(Number.parseInt(event.currentTarget.value, 10))}
                >
                    <For each={[5, 10, 20, 50]}>{(size) => <option value={size}>{size}</option>}</For>
                </select>
            </label>
        </form>
    )
}

// frontend-v2/src/app/shared/ui/collection-toolbar/collection-toolbar.component.ts
import { Component, input, linkedSignal, output } from '@angular/core';
import { Button } from '../button/button.component';
import type { CollectionSortDirection } from '../../services/collection-types';

export type CollectionSortOption = {
  label: string;
  value: string;
};

@Component({
  selector: 'app-collection-toolbar',
  imports: [Button],
  templateUrl: './collection-toolbar.component.html',
})
export class CollectionToolbar {
  search = input.required<string>();
  searchPlaceholder = input.required<string>();
  sortBy = input.required<string>();
  sortDirection = input.required<CollectionSortDirection>();
  pageSize = input.required<number>();
  sortOptions = input.required<CollectionSortOption[]>();

  searchChange = output<string>();
  sortByChange = output<string>();
  sortDirectionChange = output<CollectionSortDirection>();
  pageSizeChange = output<number>();

  protected readonly pageSizeOptions = [5, 10, 20, 50];
  // linkedSignal, not signal(this.search()) — required inputs aren't
  // readable at construction time (NG8118), and linkedSignal is the
  // supported pattern for a writable local draft seeded from (and
  // re-synced when) a reactive source changes. This differs slightly from
  // Solid's createSignal(props.search), which only reads the initial
  // value and never re-syncs — accepted as the more correct behavior
  // (the toolbar's draft should reflect an externally-reset search).
  protected searchDraft = linkedSignal(() => this.search());

  protected submitSearch(event: SubmitEvent) {
    event.preventDefault();
    this.searchChange.emit(this.searchDraft().trim());
  }

  protected onSearchInput(event: Event) {
    this.searchDraft.set((event.target as HTMLInputElement).value);
  }

  protected onSortByChange(event: Event) {
    this.sortByChange.emit((event.target as HTMLSelectElement).value);
  }

  protected onSortDirectionChange(event: Event) {
    this.sortDirectionChange.emit(
      (event.target as HTMLSelectElement).value as CollectionSortDirection,
    );
  }

  protected onPageSizeChange(event: Event) {
    this.pageSizeChange.emit(Number.parseInt((event.target as HTMLSelectElement).value, 10));
  }
}

<form
  class="grid gap-3 lg:grid-cols-[minmax(14rem,1fr)_minmax(10rem,0.5fr)_auto_auto]"
  (submit)="submitSearch($event)"
>
  <label class="space-y-1 text-sm text-gray-600">
    <span class="font-medium text-gray-800">Search</span>
    <div class="flex gap-2">
      <input
        type="search"
        [value]="searchDraft()"
        [placeholder]="searchPlaceholder()"
        class="min-w-0 flex-1 rounded-md border border-gray-300 px-3 py-2 text-sm"
        (input)="onSearchInput($event)"
      />
      <app-button type="submit" color="alternative" size="sm">Search</app-button>
    </div>
  </label>

  <label class="space-y-1 text-sm text-gray-600">
    <span class="font-medium text-gray-800">Sort</span>
    <select
      [value]="sortBy()"
      class="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
      (change)="onSortByChange($event)"
    >
      @for (option of sortOptions(); track option.value) {
        <option [value]="option.value">{{ option.label }}</option>
      }
    </select>
  </label>

  <label class="space-y-1 text-sm text-gray-600">
    <span class="font-medium text-gray-800">Direction</span>
    <select
      [value]="sortDirection()"
      class="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
      (change)="onSortDirectionChange($event)"
    >
      <option value="SORT_DIRECTION_DESC">Descending</option>
      <option value="SORT_DIRECTION_ASC">Ascending</option>
    </select>
  </label>

  <label class="space-y-1 text-sm text-gray-600">
    <span class="font-medium text-gray-800">Rows</span>
    <select
      [value]="pageSize()"
      class="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
      (change)="onPageSizeChange($event)"
    >
      @for (size of pageSizeOptions; track size) {
        <option [value]="size">{{ size }}</option>
      }
    </select>
  </label>
</form>
