// internal/ui-podzone/src/solid/components/common/SectionTitle.tsx
import { Show } from 'solid-js'

export function SectionTitle(props: { title: string; subtitle?: string }) {
  return (
    <div class="space-y-1">
      <h2 class="text-base font-semibold text-gray-950">{props.title}</h2>
      <Show when={props.subtitle}>
        <p class="text-sm text-gray-600">{props.subtitle}</p>
      </Show>
    </div>
  )
}

// frontend-v2/src/app/shared/ui/section-title/section-title.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-section-title',
  templateUrl: './section-title.component.html',
})
export class SectionTitle {
  title = input.required<string>();
  subtitle = input<string>();
}

<div class="space-y-1">
  <h2 class="text-base font-semibold text-gray-950">{{ title() }}</h2>
  @if (subtitle()) {
    <p class="text-sm text-gray-600">{{ subtitle() }}</p>
  }
</div>
