// internal/ui-podzone/src/solid/components/common/display/ChatBubble.tsx
import { Show } from 'solid-js'
import { classes } from '../../../shared/utils'

export type ChatBubbleProps = {
  author?: string
  copy: string
  meta?: string
  align?: 'start' | 'end'
  class?: string
}

export function ChatBubble(props: ChatBubbleProps) {
  const isEnd = () => props.align === 'end'

  return (
    <div class={classes('flex w-full', isEnd() ? 'justify-end' : 'justify-start', props.class)}>
      <div
        class={classes(
          'max-w-xl rounded-lg px-4 py-3 shadow-sm',
          isEnd() ? 'bg-gray-950 text-white' : 'bg-white text-gray-900 ring-1 ring-gray-200'
        )}
      >
        <Show when={props.author || props.meta}>
          <div
            class={classes(
              'mb-1 flex flex-wrap items-center gap-2 text-xs',
              isEnd() ? 'text-gray-300' : 'text-gray-500'
            )}
          >
            <Show when={props.author}>
              <span class="font-semibold">{props.author}</span>
            </Show>
            <Show when={props.meta}>
              <span>{props.meta}</span>
            </Show>
          </div>
        </Show>
        <p class="text-sm leading-6">{props.copy}</p>
      </div>
    </div>
  )
}

// frontend-v2/src/app/shared/ui/chat-bubble/chat-bubble.component.ts
import { Component, computed, input } from '@angular/core';
import { classes } from '../../utils';

@Component({
  selector: 'app-chat-bubble',
  templateUrl: './chat-bubble.component.html',
})
export class ChatBubble {
  author = input<string>();
  copy = input.required<string>();
  meta = input<string>();
  align = input<'start' | 'end'>('start');
  class = input<string>();

  protected isEnd = computed(() => this.align() === 'end');

  protected wrapperClass = computed(() =>
    classes('flex w-full', this.isEnd() ? 'justify-end' : 'justify-start', this.class()),
  );

  protected bubbleClass = computed(() =>
    classes(
      'max-w-xl rounded-lg px-4 py-3 shadow-sm',
      this.isEnd() ? 'bg-gray-950 text-white' : 'bg-white text-gray-900 ring-1 ring-gray-200',
    ),
  );

  protected metaClass = computed(() =>
    classes(
      'mb-1 flex flex-wrap items-center gap-2 text-xs',
      this.isEnd() ? 'text-gray-300' : 'text-gray-500',
    ),
  );
}

<div [class]="wrapperClass()">
  <div [class]="bubbleClass()">
    @if (author() || meta()) {
      <div [class]="metaClass()">
        @if (author()) {
          <span class="font-semibold">{{ author() }}</span>
        }
        @if (meta()) {
          <span>{{ meta() }}</span>
        }
      </div>
    }
    <p class="text-sm leading-6">{{ copy() }}</p>
  </div>
</div>
