// internal/ui-podzone/src/solid/components/common/display/ButtonGroup.tsx
import type { ParentProps } from 'solid-js'
import { classes } from '../../../shared/utils'

export function ButtonGroup(props: ParentProps<{ class?: string }>) {
  return (
    <div
      role="group"
      class={classes('inline-flex flex-wrap items-center gap-2', props.class)}
    >
      {props.children}
    </div>
  )
}

// frontend-v2/src/app/shared/ui/button-group/button-group.component.ts
import { Component, computed, input } from '@angular/core';
import { classes } from '../../utils';

@Component({
  selector: 'app-button-group',
  templateUrl: './button-group.component.html',
})
export class ButtonGroup {
  class = input<string>();

  protected className = computed(() =>
    classes('inline-flex flex-wrap items-center gap-2', this.class()),
  );
}

<div role="group" [class]="className()"><ng-content /></div>
