// internal/ui-podzone/src/solid/components/common/Link.tsx
import { Link as RouterLink } from '@tanstack/solid-router'
import { splitProps, type JSX } from 'solid-js'
import { isExternalUrl } from '../../shared/utils'

export type LinkProps = JSX.AnchorHTMLAttributes<HTMLAnchorElement> & {
    href: string
    class?: string
}

export function Link(props: LinkProps) {
    const [local, rest] = splitProps(props, ['href', 'class', 'children', 'target', 'rel'])

    if (isExternalUrl(local.href)) {
        const rel = local.target === '_blank' ? (local.rel ?? 'noopener noreferrer') : local.rel
        return (
            <a href={local.href} target={local.target} rel={rel} class={local.class} {...rest}>
                {local.children}
            </a>
        )
    }

    return (
        <RouterLink to={local.href} class={local.class} {...(rest as object)}>
            {local.children}
        </RouterLink>
    )
}

// frontend-v2/src/app/shared/ui/link/link.component.ts
import { Component, computed, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { isExternalUrl } from '../../utils';

@Component({
  selector: 'app-link',
  imports: [RouterLink],
  templateUrl: './link.component.html',
})
export class Link {
  href = input.required<string>();
  target = input<string>();
  class = input<string>();

  protected isExternal = computed(() => isExternalUrl(this.href()));
  protected rel = computed(() => (this.target() === '_blank' ? 'noopener noreferrer' : undefined));
}

@if (isExternal()) {
  <a [href]="href()" [target]="target()" [rel]="rel()" [class]="class()"><ng-content /></a>
} @else {
  <a [routerLink]="href()" [class]="class()"><ng-content /></a>
}
